language: node_js
sudo: false
notifications:
  email: false
node_js:
  - "16"
  - "14"
  - "12"
before_install:
  - npm install -g npm@latest
before_script:
  - npm prune
install:
  - npm install
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
